<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="4" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-10-19T13:29:12 IST" name="Suite" finished-at="2024-10-19T13:29:56 IST" duration-ms="43986">
    <groups>
    </groups>
    <test started-at="2024-10-19T13:29:12 IST" name="Test" finished-at="2024-10-19T13:29:56 IST" duration-ms="43986">
      <class name="testclasses.TestLogin">
        <test-method is-config="true" signature="Initialize()[pri:0, instance:testclasses.TestLogin@41a0aa7d]" started-at="2024-10-19T13:29:12 IST" name="Initialize" finished-at="2024-10-19T13:29:26 IST" duration-ms="14112" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Initialize -->
        <test-method signature="VerifyLoginPage()[pri:0, instance:testclasses.TestLogin@41a0aa7d]" started-at="2024-10-19T13:29:26 IST" name="VerifyLoginPage" finished-at="2024-10-19T13:29:46 IST" duration-ms="19245" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyLoginPage -->
        <test-method is-config="true" signature="cleanup()[pri:0, instance:testclasses.TestLogin@41a0aa7d]" started-at="2024-10-19T13:29:56 IST" name="cleanup" finished-at="2024-10-19T13:29:56 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanup -->
      </class> <!-- testclasses.TestLogin -->
      <class name="testclasses.TestRegister">
        <test-method signature="verifyRegister()[pri:0, instance:testclasses.TestRegister@60099951]" started-at="2024-10-19T13:29:46 IST" name="verifyRegister" finished-at="2024-10-19T13:29:56 IST" duration-ms="10475" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[ element does not contains Your account was created successfully. You are now logged in. it contains If you have an account with us you can sign-up for free instant online access. You will have to provide some personal information.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException:  element does not contains Your account was created successfully. You are now logged in. it contains If you have an account with us you can sign-up for free instant online access. You will have to provide some personal information.
at dev.failsafe.internal.util.Assert.isTrue(Assert.java:29)
at helpers.WebElementExtension.ElementContainsText(WebElementExtension.java:39)
at testclasses.TestRegister.verifyRegister(TestRegister.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyRegister -->
      </class> <!-- testclasses.TestRegister -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
